spring:
  application:
    name: jam-hub-service
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, resilience4j, resilience4j.circuitbreakers, resilience4j.rate-limiters, resilience4j.bulkheads
  health:
    circuitbreakers:
      enabled: true